name: HotBleuskyBot

on:
  schedule:
    - cron: "8,38 * * * *"
  workflow_dispatch:


permissions:
  contents: write

concurrency:
  group: hotbleuskybot
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      BSKY_USERNAME: ${{ secrets.BSKY_USERNAME_HOTBLEUSKY }}
      BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD_HOTBLEUSKY }}

      STATE_FILE: state_hotbleusky.json
      MAX_PER_RUN: 100
      MAX_PER_USER: 3
      HOURS_BACK: 3
      SLEEP_SECONDS: 2

      LIST_MEMBER_LIMIT: 1500
      AUTHOR_POSTS_PER_MEMBER: 30
      FEED_MAX_ITEMS: 500
      HASHTAG_MAX_ITEMS: 100

      PROMO_RANDOM_POOL: 25
      PROMO_FETCH_PER_MEMBER: 100

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install atproto

      - name: Run HotBleusky bot
        run: python hotbleusky_reposter.py

      - name: Commit state file
        if: always()
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          if [ -f state_hotbleusky.json ]; then
            git add state_hotbleusky.json
            git diff --cached --quiet || git commit -m "Update HotBleusky state"
            git push
          else
            echo "No state file found"
          fi
